# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField()),
                ('label', models.CharField(max_length=72)),
                ('thumbnail_path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.IntegerField()),
                ('label', models.CharField(max_length=72)),
                ('description', models.CharField(max_length=250)),
                ('upload_time', models.DateTimeField()),
                ('file_path', models.CharField(max_length=1000)),
                ('belong_album_1', models.BooleanField()),
                ('belong_album_2', models.BooleanField()),
                ('belong_album_3', models.BooleanField()),
                ('belong_album_4', models.BooleanField()),
                ('belong_album_5', models.BooleanField()),
                ('belong_album_6', models.BooleanField()),
            ],
        ),
    ]
