# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_id',
        ),
    ]
